require("truehl.plugins-setup")
require("truehl.core.options")
require("truehl.core.keymaps")
require("truehl.core.colorscheme")
require("truehl.plugins.comment")
require("truehl.plugins.nvim-tree")
require("truehl.plugins.lualine")
require("truehl.plugins.telescope")
